baseURL = 'https://dfx.is'
languageCode = 'en-us'
title = 'dfx.is'
theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

enableEmoji = true

[params]
  description = "A small collection of... things."
  copyright = "Copyright © 2023"
  footer = "Made with ♥ Using Hugo"
  dark = "auto"
  highlight = true
  
[menu]
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30
    
[permalinks]
  posts = "/:title/"
  
[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = false
  
  [markup.tableOfContents]
    ordered = true